### ISSUE TITLE
Not launching on SteamOS

### ISSUE THREAD

**Issue by ShadowKitty9** [koxx12-dev/Skyclient-installer-Java#49]
Im on my Steam Deck and every time I click the .jar file, it just opens it as a .zip file. is there a command I can use to get it?

**Comment by ShadowKitty9** [comment]
nvm, got it. for those who have the same problem in the future, use "git clone" and the link to the GitHub

**Comment by ShadowKitty9** [comment]
but no what don't know what to do, plz help

**Comment by Wyvest** [comment]
Please make a ticket at https://inv.wtf/skyclient
