### ISSUE TITLE
Installer only working with java 8

### ISSUE THREAD

**Issue by theskyblockman** [koxx12-dev/Skyclient-installer-Java#7]
Hey,

there is some compatibility errors that's make's you only able to use java 8 or, as a dev and for the new 1.16 of minecraft I needed to install java 16 so I wish that you can give more compatibility to this

**Comment by koxx12-dev** [comment]
as this is made with bad unoptimized code I'm slowly working on a rewrite 
Also you can use mutilple java versions if you just run `java/javaw` with args `-jar jarnamehere.jar` in the bin directory of that java version

**Comment by theskyblockman** [comment]
I know but lucky for me, Im a dev so I already know this but this installer is for public not dev so ppl don't always know that

Also thanks for the reactivity you had to respond and im happy to know that a rewrite is making!

**Comment by koxx12-dev** [comment]
rewrite it out!
