### ISSUE TITLE
Not workin with Java 17

### ISSUE THREAD

**Issue by TillDV** [koxx12-dev/Skyclient-installer-Java#8]
It does not work with Java 17 and Java 8 is also not working

**Comment by koxx12-dev** [comment]
1. If you can't run it with java 8 that prob means you done something wrong
2. It doesnt work with java 17 cuz of one lib
3. I'm slowly rewriting it so it will work on java 8+ later

**Comment by koxx12-dev** [comment]
rewrite is out so it should work with java 17
